parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\BookAction:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/BookAction/Domain'
                prefix: 'App\BookAction\Domain'
                alias: AppBookAction
            App\Catalog:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Catalog/Model'
                prefix: 'App\Catalog\Model'
                alias: AppCatalog
            App\Receiver:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Receiver/Model'
                prefix: 'App\Receiver\Model'
                alias: AppReceiver
            App\Security:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Security/Model'
                prefix: 'App\Security\Model'
                alias: AppShared
