book_action_controllers:
    resource: ../../src/BookAction/Controller/
    type: annotation
catalog_controllers:
    resource: ../../src/Catalog/Controller/
    type: annotation
receiver_controllers:
    resource: ../../src/Receiver/Controller/
    type: annotation
security_controllers:
    resource: ../../src/Security/Controller/
    type: annotation
