website_index:
    path: /
    controller: App\Shared\Controller\WebsiteController::index
    methods: [GET]
website_receivers:
    path: /receivers
    controller: App\Shared\Controller\WebsiteController::receivers
    methods: [GET]
bookshelf_index:
    path: /books
    controller: App\BookAction\Controller\BookshelfController::index
    methods: [GET]
bookshelf_receive:
    path: /receive/{id}
    controller: App\BookAction\Controller\BookshelfController::receive
    methods: [POST]
bookshelf_release:
    path: /release/{id}
    controller: App\BookAction\Controller\BookshelfController::release
    methods: [POST]
bookshelf_sell:
    path: /sell/{id}
    controller: App\BookAction\Controller\BookshelfController::sell
    methods: [POST]
book_form:
    path: /books/form
    controller: App\Catalog\Controller\WebsiteController:form
    methods: [GET]
book_new:
    path: /books
    controller: App\Catalog\Controller\BookController::new
    methods: [POST]
book_one:
    path: /books/{id}
    controller: App\Catalog\Controller\BookController:one
    methods: [GET]
book_edit:
    path: /books/{id}
    controller: App\Catalog\Controller\BookController:edit
    methods: [PUT]
book_delete:
    path: /books/{id}
    controller: App\Catalog\Controller\BookController:delete
    methods: [DELETE]
receiver_new:
    path: /receiver
    controller: App\Receiver\Controller\ReceiverController:new
    methods: [POST]
receiver_index:
    path: /receiver
    controller: App\Receiver\Controller\ReceiverController:index
    methods: [GET]
receiver_one:
    path: /receiver/{id}
    controller: App\Receiver\Controller\ReceiverController:one
    methods: [GET]
receiver_delete:
    path: /receiver/{id}
    controller: App\Receiver\Controller\ReceiverController:delete
    methods: [DELETE]
receiver_edit:
    path: /receiver/{id}
    controller: App\Receiver\Controller\ReceiverController:edit
    methods: [PUT]
app_login:
    path: /login
    controller: App\Shared\Controller\SecurityController:login
    methods: [GET, POST]
app_logout:
    path: /logout
    controller: App\Shared\Controller\SecurityController:logout
    methods: [GET]
