catalog_show:
    path: /
    controller: App\Catalog\Controller\BookController:show
    methods: [GET]
catalog_index:
    path: /books
    controller: App\Catalog\Controller\BookController:index
    methods: [GET]
catalog_form:
    path: /books/form
    controller: App\Catalog\Controller\BookController:form
    methods: [GET]
catalog_new:
    path: /books
    controller: App\Catalog\Controller\BookController::new
    methods: [POST]
catalog_one:
    path: /books/{id}
    controller: App\Catalog\Controller\BookController:one
    methods: [GET]
catalog_edit:
    path: /books/{id}
    controller: App\Catalog\Controller\BookController:edit
    methods: [PUT]
catalog_delete:
    path: /books/{id}
    controller: App\Catalog\Controller\BookController:delete
    methods: [DELETE]
book_action_index:
    path: /bookaction/{bookId}
    controller: App\BookAction\Controller\IndexController:indexActionsForBook
    methods: [GET]
book_action_receive:
    path: /receive/{id}
    controller: App\BookAction\Controller\ReceiveBookController::receive
    methods: [POST]
book_action_release:
    path: /release/{id}
    controller: App\BookAction\Controller\ReleaseBookController::release
    methods: [POST]
book_action_sell:
    path: /sell/{id}
    controller: App\BookAction\Controller\SellBookController::sell
    methods: [POST]
receiver_show:
    path: /receivers
    controller: App\Receiver\Controller\ReceiverController:show
    methods: [GET]
receiver_new:
    path: /receiver
    controller: App\Receiver\Controller\ReceiverController:new
    methods: [POST]
receiver_index:
    path: /receiver
    controller: App\Receiver\Controller\ReceiverController:index
    methods: [GET]
receiver_one:
    path: /receiver/{id}
    controller: App\Receiver\Controller\ReceiverController:one
    methods: [GET]
receiver_delete:
    path: /receiver/{id}
    controller: App\Receiver\Controller\ReceiverController:delete
    methods: [DELETE]
receiver_edit:
    path: /receiver/{id}
    controller: App\Receiver\Controller\ReceiverController:edit
    methods: [PUT]
security_login:
    path: /login
    controller: App\Security\Controller\SecurityController:login
    methods: [GET, POST]
security_logout:
    path: /logout
    controller: App\Security\Controller\SecurityController:logout
    methods: [GET]
