website_index:
    path: /
    controller: App\Controller\WebsiteController::index
    methods: [GET]
bookshelf_index:
    path: /books
    controller: App\Controller\BookshelfController::index
    methods: [GET]
bookshelf_receive:
    path: /receive/{id}
    controller: App\Controller\BookshelfController::receive
    methods: [POST]
bookshelf_release:
    path: /release/{id}
    controller: App\Controller\BookshelfController::release
    methods: [POST]
bookshelf_sell:
    path: /sell/{id}
    controller: App\Controller\BookshelfController::sell
    methods: [POST]
book_new:
    path: /books
    controller: App\Controller\BookController::new
    methods: [POST]
book_edit:
    path: /books/{id}
    controller: App\Controller\BookController:edit
    methods: [PUT]
receiver_new:
    path: /receiver
    controller: App\Controller\ReceiverController:new
    methods: [POST]

