website_index:
    path: /
    controller: App\Controller\WebsiteController::index
    methods: [GET]
author_index:
    path: /authors
    controller: App\Controller\BookshelfController::index
    methods: [GET]
book_new:
    path: /books
    controller: App\Controller\BookController::new
    methods: [POST]
